name: warrden

services:
  warrden:
    image: code.neureka.dev/warrden/warrden:latest
    container_name: warrden
    environment:
      - APP_VERSION=latest
      - CONFIG_PATH=/app/data/config.yaml
      - DATABASE_PATH=/app/data/warden.db
      - DRY_RUN=false
      - PGID=1000
      - PUID=1000
      - TZ=UTC
    networks:
      - warrden
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  warrden:
    name: warrden
