name: warrden

services:
  warrden:
    image: code.neureka.dev/warrden/warrden:3
    container_name: warrden
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - DATABASE_PATH=/app/data/warden.db
      - CONFIG_PATH=/app/data/config.yaml
    networks:
      - warrden
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  warrden:
    name: warrden
