name: build-container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-build-container:
    name: "Setup Build: Container"
    uses: forgejo/workflows/.forgejo/workflows/build-container.yaml@main
    with:
      job-name: "Build: Container"
      context: .
      file: Dockerfile
      images: code.neureka.dev/org/image
      platforms: linux/amd64,linux/arm64
      tags: |
        type=raw,value=edge
      build-args: APP_VERSION=edge-${{ forgejo.sha }}
      push: true
    secrets:
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
