name: build-container

on:
  push:
    tags:
      - "*.*.*"

jobs:
  setup-build-container:
    name: "Setup Build: Container"
    uses: forgejo/workflows/.forgejo/workflows/build-container.yaml@main
    with:
      job-name: "Build: Container"
      context: .
      file: Dockerfile
      platforms: linux/amd64,linux/arm64
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        latest
      build-args: APP_VERSION=${{ forgejo.ref_name }}
      push: true
    secrets:
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
